smooth:
	python script/smoothing.py

convolve:
	python script/convolution.py
	
glm:
	python script/glm.py

normality:
	python script/normality.py

conclusion:
	python script/conclusion.py

all:
	python script/smoothing.py

	python script/convolution.py
	
	python script/glm.py

	python script/normality.py

	python script/conclusion.py

clean: