smooth:
	python smoothing.py

convolve:
	python convolution.py
	
glm:
	python glm.py

normality:
	python normality.py

conclusion:
	conclusion.py

all:
	python smoothing.py

	python convolution.py
	
	python glm.py

	python normality.py

	conclusion.py

clean: